version: '2'
services:
  db:
    build: ./db
    environment:
      - MYSQL_DATABASE=ritz
      - MYSQL_ROOT_PASSWORD=password
      - TZ=Japan
    networks:
      - default
    ports:
      - '24001:3306'
    volumes:
      - ./misc/data:/var/lib/mysql
      - ./sql:/sql
    restart: always

  jupyter:
    build: ./jupyter
    environment:
      - GRANT_SUDO=yes
      - PASSWORD=password
    volumes:
      - ./jupyter/work/:/home/jovyan/work/
    ports:
      - '24000:8888'
    command: bash -c "rm /home/jovyan/.cache/matplotlib/fontList.py3k.cache && start-notebook.sh --NotebookApp.token='kgps8fsa24fff'"
    restart: always
