version: '2'
services:
  db:
    build: ./db
    environment:
      - MYSQL_DATABASE=ritz
      - MYSQL_ROOT_PASSWORD=password
      - TZ=Japan
    networks:
      - default
    ports:
      - '24001:3306'
    volumes:
      - ./misc/data:/var/lib/mysql
      - ./sql:/sql
    restart: always

  jupyter:
    build: ./jupyter
    volumes:
      - ./jupyter/work/:/home/jovyan/work/
    ports:
      - '24000:8888'
    restart: always
